Repository SU-SWS/vpge_profile, pull requests merged in 2023-11, with the labels that each got.

#69 VGGD-25 - importing localist images
  config/splits/vpge/config_split.patch.core.entity_view_display.node.stanford_event.default.yml
  config/sync/migrate_plus.migration.stanford_localist_importer.yml
Labels: size/xs

#72 VGGD-27 - enabled "Apply Filter" and BEF tweak.
  config/splits/vpge/views.view.vpge_grad_grow.yml
Labels: size/xs

#73 Vggd 28 shs patch
  composer.json
Labels: size/xs, patch

#70 VGGD-26 | @jdwjdwjdw | Update view mode pattern UI
  composer.json
  config/splits/vpge/core.entity_view_display.node.resource.grad_grow_card.yml
  config/splits/vpge/core.entity_view_display.node.stanford_event.grad_grow_card.yml
  config/splits/vpge/views.view.vpge_grad_grow.yml
  config/splits/vpge/views.view.vpge_resources.yml
  config/sync/config_split.config_split.default.yml
  config/sync/config_split.config_split.diversityworks.yml
  config/sync/filter.format.stanford_minimal_html.yml
  config/sync/migrate_plus.migration.stanford_localist_importer.yml
  themes/vpge/dist/vpge.styles.css
  themes/vpge/lib/scss/components/grad-grow-filter/_grad-grow-filter.scss
  themes/vpge/lib/scss/components/grad-grow-filter/index.scss
  themes/vpge/lib/scss/components/index.scss
  themes/vpge/templates/components/grad-grow-event-card/pattern-events-card--layout--node--stanford-event--grad-grow-card.html.twig
  themes/vpge/templates/components/grad-grow-resource-card/pattern-card--layout--node--resource--grad-grow-card.html.twig
  themes/vpge/templates/views/views-view--vpge-grad-grow--filters-block.html.twig
  themes/vpge/vpge.theme
Labels: size/l

#74 Replace gradgrow filters with decoupled filters
  config/splits/vpge/views.view.vpge_grad_grow.yml
  modules/custom/vpga_profile_helper/composer.json
  modules/custom/vpga_profile_helper/vpge_profile_helper.module
  themes/vpge/lib/js/gradgrow-filters/.env
  themes/vpge/lib/js/gradgrow-filters/.gitignore
  themes/vpge/lib/js/gradgrow-filters/.nvmrc
  themes/vpge/lib/js/gradgrow-filters/dist/index.html
  themes/vpge/lib/js/gradgrow-filters/dist/islands/gradgrow-filters.island.js
  themes/vpge/lib/js/gradgrow-filters/package.json
  themes/vpge/lib/js/gradgrow-filters/src/gradgrow-filters.island.tsx
  themes/vpge/lib/js/gradgrow-filters/src/select-list.tsx
  themes/vpge/lib/js/gradgrow-filters/src/template.html
  themes/vpge/lib/js/gradgrow-filters/tsconfig.json
  themes/vpge/lib/js/gradgrow-filters/webpack.config.js
  themes/vpge/lib/js/gradgrow-filters/yarn.lock
  themes/vpge/templates/views/views-view--vpge-grad-grow--filters-block.html.twig
  themes/vpge/vpge.libraries.yml
  themes/vpge/vpge.theme
Labels: size/xl

#76 Fix grad grow filter card pill styles
  themes/vpge/dist/vpge.styles.css
  themes/vpge/lib/scss/components/grad-grow-filter/_grad-grow-filter.scss
Labels: size/xs

#77 Update Grad Grow filter results font-size and padding-right for mobile
  themes/vpge/dist/vpge.styles.css
  themes/vpge/lib/scss/components/grad-grow-filter/_grad-grow-filter.scss
Labels: size/xs

#78 11.1.0
  .github/workflows/tests.yml
  CHANGELOG.md
  vpge_profile.info.yml
Labels: size/xs, minor
