Repository SU-SWS/vpge_profile, pull requests merged in 2023-10, with the labels that each got.

#57 FIXUP - update path on library file for css.
  themes/vpge/vpge.libraries.yml
Labels: size/xs

#59 Disable page_cache_query_ignore
  config/sync/core.extension.yml
  config/sync/page_cache_query_ignore.settings.yml
Labels: size/xs

#56 VGGD-16 Add centered overlapping banner variant
  themes/vpge/dist/vpge.styles.css
  themes/vpge/lib/scss/components/banner/_banner--centered-overlapping.scss
  themes/vpge/lib/scss/components/banner/index.scss
  themes/vpge/lib/scss/components/card/_card.scss
  themes/vpge/lib/scss/components/card/index.scss
  themes/vpge/lib/scss/components/index.scss
  themes/vpge/lib/scss/vpge.scss
  themes/vpge/vpge.react_behaviors.yml
  themes/vpge/vpge.theme
Labels: size/xl

#60 11.0.0
  CHANGELOG.md
  vpge_profile.info.yml
Labels: size/s

#62 11.0.1
  CHANGELOG.md
  vpge_profile.info.yml
Labels: size/xs, patch

#63 11.0.2
  CHANGELOG.md
  tests/codeception/acceptance/Content/PolicyCest.php
  vpge_profile.info.yml
Labels: size/xs, patch

#64 11.0.3
  CHANGELOG.md
  vpge_profile.info.yml
Labels: size/xs, patch

#65 11.0.4
  CHANGELOG.md
  vpge_profile.info.yml
Labels: size/xs, patch

#66 VGGD-14 -- grad grow filters
  composer.json
  config/splits/vpge/config_split.patch.core.entity_form_display.node.stanford_event.default.yml
  config/splits/vpge/config_split.patch.core.entity_form_display.node.stanford_news.default.yml
  config/splits/vpge/config_split.patch.core.entity_form_display.node.stanford_person.default.yml
  config/splits/vpge/config_split.patch.core.entity_view_display.node.stanford_event.default.yml
  config/splits/vpge/config_split.patch.core.entity_view_display.node.stanford_event.search_indexing.yml
  config/splits/vpge/config_split.patch.core.entity_view_display.node.stanford_event.stanford_card.yml
  config/splits/vpge/config_split.patch.core.entity_view_display.node.stanford_event.teaser.yml
  config/splits/vpge/config_split.patch.core.entity_view_display.node.stanford_news.default.yml
  config/splits/vpge/config_split.patch.core.entity_view_display.node.stanford_news.search_indexing.yml
  config/splits/vpge/config_split.patch.core.entity_view_display.node.stanford_news.stanford_card.yml
  config/splits/vpge/config_split.patch.core.entity_view_display.node.stanford_page.default.yml
  config/splits/vpge/config_split.patch.core.entity_view_display.node.stanford_page.search_indexing.yml
  config/splits/vpge/config_split.patch.core.entity_view_display.node.stanford_person.default.yml
  config/splits/vpge/config_split.patch.core.entity_view_display.node.stanford_person.search_indexing.yml
  config/splits/vpge/config_split.patch.core.entity_view_display.node.stanford_person.stanford_card.yml
  config/splits/vpge/config_split.patch.core.entity_view_display.node.stanford_person.teaser.yml
  config/splits/vpge/config_split.patch.user.role.layout_builder_user.yml
  config/splits/vpge/config_split.patch.user.role.site_manager.yml
  config/splits/vpge/core.entity_view_display.node.resource.grad_grow_card.yml
  config/splits/vpge/core.entity_view_display.node.stanford_event.grad_grow_card.yml
  config/splits/vpge/core.entity_view_mode.block_content.grad_grow_card.yml
  config/splits/vpge/core.entity_view_mode.node.grad_grow_card.yml
  config/splits/vpge/field.field.node.fellowship_funding.body.yml
  config/splits/vpge/field.field.node.fellowship_funding.su_vpge_fellowship_apply_now.yml
  config/splits/vpge/field.field.node.fellowship_funding.su_vpge_fellowship_contact.yml
  config/splits/vpge/field.field.node.fellowship_funding.su_vpge_fellowship_how_apply.yml
  config/splits/vpge/field.field.node.partner.body.yml
  config/splits/vpge/field.field.node.program.body.yml
  config/splits/vpge/field.field.node.program.su_vpge_registration_process.yml
  config/splits/vpge/field.field.node.resource.body.yml
  config/splits/vpge/field.field.node.stanford_event.su_vpge_featured_image.yml
  config/splits/vpge/field.field.node.stanford_news.body.yml
  config/splits/vpge/field.storage.node.su_vpge_featured_image.yml
  config/splits/vpge/views.view.feeds_feed.yml
  config/splits/vpge/views.view.grad_grow_competency_navigation_block.yml
  config/splits/vpge/views.view.vpge_content.yml
  config/splits/vpge/views.view.vpge_grad_grow.yml
  config/sync/config_ignore.settings.yml
  config/sync/config_split.config_split.default.yml
  config/sync/core.extension.yml
  themes/vpge/templates/views/views-view--vpge-grad-grow.html.twig
  themes/vpge/vpge.theme
Labels: size/xl

#68 11.0.6
  CHANGELOG.md
  vpge_profile.info.yml
Labels: size/xs, patch

#61 VGGD-16 | @jdwjdwjdw | Update grad grow card link styles
  themes/vpge/dist/vpge.styles.css
  themes/vpge/lib/scss/components/card/_card.scss
Labels: size/xs
