Repository SU-SWS/vpge_profile, pull requests merged in 2024-02, with the labels that each got.

#83 Fix inheritance
  composer.json
  config/sync/core.extension.yml
  config/sync/filter.format.stanford_minimal_html.yml
  tests/codeception/acceptance/SubThemeCest.php
  vpge_profile.install
Labels: size/xs

#82 VPGE-54: updated field labels
  config/splits/vpge/field.field.node.fellowship_funding.su_vpge_fellowship_app_period.yml
  config/splits/vpge/field.field.node.fellowship_funding.su_vpge_fellowship_how_apply.yml
  config/splits/vpge/views.view.vpge_content_fields_on_a_node.yml
  src/VpgeProfilePermissions.php
  tests/codeception/acceptance/Content/BasicPageCest.php
  tests/codeception/acceptance/Content/DefaultContentCest.php
  tests/codeception/acceptance/Content/PublicationsCest.php
  tests/src/Kernel/EventSubscriber/EventSubscriberTest.php
  tests/src/Kernel/VpgeProfilePermissionsTest.php
Labels: size/m

#84 Test fixup
  tests/codeception/acceptance/Content/BasicPageCest.php
Labels: size/xs

#85 11.2.0
  CHANGELOG.md
  themes/diversityworks/templates/block--diversityworks-search.html.twig
  themes/vpge/templates/block--vpge-search.html.twig
  vpge_profile.info.yml
Labels: size/xs, minor
